### ISSUE TITLE
serializedSize(): Always return a double (to lower the risk for integer overflow downstream)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/parallelly#123]
# Background

The `serializedSize()` function returns the number of bytes it would take to serialize an object. It returns an integer, unless it is greater than `.Machine$integer.max` (= ~2.15 GB), in case it returns a double (https://github.com/futureverse/parallelly/blob/88783a6501edfed29d826640d3433b0a159c84a1/src/calc-serialized-size.c#L74-L78).

# Issue

This agility of `serializedSize()` to return an integer, if sufficient, can lead to silent errors downstream.  For instance, two objects might be small enough to return an integer;

```r
size1 <- serializedSize(x1)
size2 <- serializedSize(x2)
```

but large enough for their sum to overflow;

```r
> size1 + size2
NA
Warning message:
In size1 + size2:
  NAs produced by integer overflow
```

This problem was first reported by @ycl6 in https://github.com/futureverse/future/pull/755.

# Suggestion

Change `serializedSize()` to always return a double. FWIW, that is what `utils::object.size()` does.

/cc @coolbutuseless

**Comment by ycl6** [comment]
Thanks @HenrikBengtsson for updating the CRAN package so swiftly!
I've been using parallelly 1.40.1-9007 and works perfectly 👍
