### ISSUE TITLE
makeClusterPSOCK(): Add a wait-and-retry mechanism for setting up nodes when they fail

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/parallelly#15]
Add a wait-and-retry mechanism for setting up nodes when they fail.  A node may fail to be set up due to the port being busy, e.g.
```r
> cl <- makeClusterPSOCK(hosts)
  Warning in makeClusterPSOCK(workers, ...) : NAs introduced by coercion
  Warning in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE, :
    port 11049 cannot be opened
  Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE, : 
    cannot open the connection
  Calls: plan ... makeClusterPSOCK -> makeNode -> <Anonymous> -> socketConnection
  Execution halted
```

_Comment_: This type of error happens occasionally on the CRAN test servers because other parallel check processes may occupy one of the ports needed by the package being tested.  I see this with the future package tests from time to time; the error often goes away the next CRAN-check cycle.

A wait-and-retry feature could be:
```r
cl <- makeClusterPSOCK(hosts, retry = 5L, sleep = 30.0)
```
which would wait 30 seconds before retrying to set up a node.  If it fails five times, no more retries will be done and the error will propagate up.

The arguments could default to:
```r
cl <- makeClusterPSOCK(hosts, 
      retry = getOption("future.makeClusterPSOCK.retry", 0L), 
      sleep = getOption("future.makeClusterPSOCK.sleep", 60))
```

**Comment by cdriveraus** [comment]
Stumbling here many years later because this still seems to be an issue occasionally. Don't have much to add but curious if there have been any developments or there are some suggested workarounds when using future.
