### ISSUE TITLE
getNproc fails when `nproc` is not found.

### ISSUE THREAD

**Issue by randy3k** [HenrikBengtsson/parallelly#58]
```
getNproc()
> Error in if (grepl("^[1-9]$", res)) return(as.integer(res)) : 
  argument is of length zero
```

In my case, [res](https://github.com/HenrikBengtsson/parallelly/blob/develop/R/availableCores.R#L385) is `NULL` which triggers the error. A simple fix is to add `if (is.null(res)) next`.

**Comment by HenrikBengtsson** [comment]
Oh my.  Fixed in parallelly (>= 1.26.1-9002). Thanks for reporting.
